[package]
name = "struct_64"
version = "0.1.0"
authors = ["Magnus Ottenklinger <evnu@posteo.de>"]
edition = "2018"

[lib]
name = "benchmark64"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
foreign-trait = { path = "foreign-trait/" }
